export const FILTERS = [
  {
    name: "Man",
  },
  {
    name: "Woman",
  },
  {
    name: "Boy",
  },
  {
    name: "Child",
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Slick formal sneaker shoe",
    price: 2999.0,
    image: "src/assets/sneakers/image-1.png",
    type: "Man",
  },
  {
    id: 2,
    name: "Slick casual sneaker shoe",
    price: 3999.0,
    image: "src/assets/sneakers/image-2.png",
    type: "Man",
  },
  {
    id: 3,
    name: "Slick sneaker shoe",
    price: 2499.0,
    image: "src/assets/sneakers/image-3.png",
    type: "Woman",
  },
  {
    id: 4,
    name: "Slick sneaker shoe",
    price: 2990.0,
    image: "src/assets/sneakers/image-4.png",
    type: "Woman",
  },
  {
    id: 5,
    name: "Slick trendy sneaker shoe",
    price: 2799.0,
    image: "src/assets/sneakers/image-5.png",
    type: "Boy",
  },
  {
    id: 6,
    name: "Slick canvas shoe",
    price: 1999.0,
    image: "src/assets/sneakers/image-6.png",
    type: "Boy",
  },
  {
    id: 7,
    name: "Slick sneaker shoe",
    price: 2499.0,
    image: "src/assets/sneakers/image-3.png",
    type: "Child",
  },
  {
    id: 8,
    name: "Slick casual sneaker shoe",
    price: 3999.0,
    image: "src/assets/sneakers/image-2.png",
    type: "Child",
  },
  {
    id: 9,
    name: "Slick formal sneaker shoe",
    price: 2999.0,
    image: "src/assets/sneakers/image-1.png",
    type: "Woman",
  },
  {
    id: 10,
    name: "Slick canvas shoe",
    price: 1999.0,
    image: "src/assets/sneakers/image-6.png",
    type: "Man",
  },
  {
    id: 11,
    name: "Slick formal sneaker shoe",
    price: 2999.0,
    image: "src/assets/sneakers/image-1.png",
    type: "Man",
  },
  {
    id: 12,
    name: "Slick casual sneaker shoe",
    price: 3999.0,
    image: "src/assets/sneakers/image-2.png",
    type: "Man",
  },
  {
    id: 13,
    name: "Slick sneaker shoe",
    price: 2499.0,
    image: "src/assets/sneakers/image-3.png",
    type: "Woman",
  },
  {
    id: 14,
    name: "Slick sneaker shoe",
    price: 2990.0,
    image: "src/assets/sneakers/image-4.png",
    type: "Woman",
  },
  {
    id: 15,
    name: "Slick trendy sneaker shoe",
    price: 2799.0,
    image: "src/assets/sneakers/image-5.png",
    type: "Boy",
  },
  {
    id: 16,
    name: "Slick canvas shoe",
    price: 1999.0,
    image: "src/assets/sneakers/image-6.png",
    type: "Boy",
  },
  {
    id: 17,
    name: "Slick sneaker shoe",
    price: 2499.0,
    image: "src/assets/sneakers/image-3.png",
    type: "Child",
  },
  {
    id: 18,
    name: "Slick casual sneaker shoe",
    price: 3999.0,
    image: "src/assets/sneakers/image-2.png",
    type: "Child",
  },
  {
    id: 19,
    name: "Slick formal sneaker shoe",
    price: 2999.0,
    image: "src/assets/sneakers/image-1.png",
    type: "Woman",
  },
  {
    id: 20,
    name: "Slick canvas shoe",
    price: 1999.0,
    image: "src/assets/sneakers/image-6.png",
    type: "Man",
  },
];
